# Generated by Django 5.1.5 on 2025-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_topics', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle_topics', models.TextField(verbose_name='Subtítulo')),
                ('title_topic_one', models.CharField(max_length=255, verbose_name='Título do Tópico 1')),
                ('description_topic_one', models.TextField(verbose_name='Subtítulo do Tópico 1')),
                ('title_topic_two', models.CharField(max_length=255, verbose_name='Título do Tópico 2')),
                ('description_topic_two', models.TextField(verbose_name='Subtítulo do Tópico2')),
                ('title_topic_three', models.CharField(max_length=255, verbose_name='Título do Tópico 3')),
                ('description_topic_three', models.TextField(verbose_name='Subtítulo do Tópico 3')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(help_text='Informe o endereço completo.', verbose_name='Endereço'),
        ),
    ]
